on: 
  release:
    types: [published]

jobs:
  update_major_version_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current major version
        id: majorv
        run: |
          release_tag="${GITHUB_REF##*/}"
          # release_json=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$release_tag)
          # echo $release_json
          # release_commit_id=$(echo $release_json | jq -r '.target_commitish')
          # echo release_commit_id=$release_commit_id | tee $GITHUB_OUTPUT
          release_version=$(echo $release_tag | sed -e 's/^v//')
          echo current_major_version=$(echo $release_version | cut -d'.' -f1) | tee $GITHUB_OUTPUT
      - name: Update major version
        run: |
          echo v$cmv
          git push origin :refs/tags/v$cmv
          git tag v$cmv $GITHUB_SHA
        env:
          cmv: ${{ steps.majorv.outputs.current_major_version }}
          # commit_id: ${{ steps.majorv.outputs.release_commit_id }}

