on:
  release:
    types: [published]

jobs:
  print_release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Release tag: $GITHUB_REF"
          echo "Release ref name: $GITHUB_REF_NAME"
