name: Print repository information

on: [push]

jobs:
  print-repository-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
      - name: Print current latest release version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest)
          tag_name=$(echo "$latest_release" | jq -r '.tag_name')
          commit_id=$(echo "$latest_release" | jq -r '.target_commitish')
          echo "latest_version=$(echo $tag_name | sed -e 's/^v//')" 
          # echo "Lastest r v: $latest_release"
          echo "Lastest r tag: $tag_name"
          echo "Lastest r commit: $commit_id"

      # - name: Get current major version
      #   run: |
      #     current_major_version=$(echo $latest_version | cut -d'.' -f1)
      #     echo "Current major version: $current_major_version"