name: Print repository information

on: [push]

jobs:
  print-repository-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
      - name: Print current latest release version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest)
          echo "Lastest r v: $latest_release"