on: 
  release:
    types: [published]

jobs:
  update_major_version_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get parts
        id: get_parts
        run: |
          echo release_tag="${GITHUB_REF_NAME}"
          release_tag="v1.2.4-ptch"
          if [[ $release_tag =~ ^v(\d+)\.(\d+)\.(\d+)(-*\w*)?$ ]]; then
            first=${BASH_REMATCH[1]}
            second=${BASH_REMATCH[2]}
            third=${BASH_REMATCH[3]}
            fourth=${BASH_REMATCH[4]}
            echo "First part: $first"
            echo "Second part: $second"
            echo "Third part: $third"
            echo "Fourth part: $fourth"
            if [[ -n $fourth ]]; then
              echo "Fourth part is not empty, exiting gracefully"
              exit 0
            fi
          else
            echo "Error: Version does not match pattern"
            exit 1
          fi