name: Released trigger
on: 
  release:
    types: [released]

jobs:
  update_major_version_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse and check version
        id: parse_check_version
          # This step uses a regex expression, which will try to parse the version tag and store it in 3 variables. 
          # Invalid version number will throw an error and stop the workflow.
          # Examples for an invalid version: v1.2, v1.2., v1.2.3-, v.1.2.3, 1.2.3, v1.2.b, 
          # v0.1.2-alpha, v0.1.2beta (for pre-releases please use the "Set as a pre-release" function of GitHub, which will not trigger this workflow)
          # Valid version will be split into 3 parts with the first part, major version number being sent to the next step.
          # Examples for a valid version: v0.1.2, v12.28.3095
        run: |
          set -e
          release_tag="${GITHUB_REF_NAME}"
          if [[ $release_tag =~ ^v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)$ ]]; then
            echo current_major_version=${BASH_REMATCH[1]} | tee --append $GITHUB_OUTPUT
            echo minor=${BASH_REMATCH[2]}
            echo build=${BASH_REMATCH[3]}
          else
            echo "Error: version does not match pattern. please make sure that a release version follows the format 'v*.*.*'."
            exit 1
          fi
      - name: Update major version
        run: |
          set -e
          git push origin :refs/tags/$v_major_version # Removes the major version tag from the old commit on remote, if it exists 
          git tag $v_major_version $GITHUB_SHA # Creates the major vesion tag on the current commit
          git push origin $v_major_version
          echo "Attached tag $v_major_version to commit $GITHUB_SHA."
        env:
          v_major_version: v${{ steps.parse_check_version.outputs.current_major_version }}



